target: demo

site:
  title: Fez
  description: JavaScript DOM components framework
  fez_url: fez.min.js
  components:
    - /site.fez
    - /fez/fez-control.fez

copy:
  "../dist/fez.min.js": "fez.min.js"
  "../dist/fez.min.js.map": "fez.min.js.map"

collections:
  changelog:
    required: [title, description, date]
