target: demo

site:
  title: Fez
  description: JavaScript DOM components framework
  fez_url: https://cdn.jsdelivr.net/gh/dux/fez@main/dist/fez.js
  components:
    - /site.fez

collections:
  blogs:
    required: [title, description, date]
